PUT http://localhost:8080/api/orders
Content-type: application/json

{
    "order_type" : "sell",
    "price" : 44.44,
    "time_of_day" : "12:09",
    "asset" : "Stock",
    "status_code" : 3,
    "num_shares" : 21,
    "ticker" : "ABBA",
}