POST http://localhost:8080/api/orders
Content-type: application/json

{
    "order_type" : "buy",
    "price" : 27.34,
    "time_of_day" : 2022-08-12 14:02:29",
    "asset" : "Stock",
    "status_code" : 3,
    "num_shares" : 21,
    "ticker" : "ABBA"
}

